version: "3.5"
services:
  mydocker:
    container_name: mydocker
    restart: unless-stopped
    build:
      dockerfile: Dockerfile5
    networks:
      - internet
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - internet
    ports: 
      - "80:8080"
    depends_on:
      - mydocker
networks:
  internet:
    name: internet
    driver: bridge
    